### ISSUE TITLE
Frontend: Make time duration display more beautiful

### ISSUE THREAD

**Issue by flymia** [YAAMSOrg/yaams-server#44]
When looking at flight duration times, the display of hours are not very nice.

In this example, it would be better if they displayed "1:50 h".

![6nabq](https://github.com/YAAMSOrg/yaams-server/assets/4712509/d6938a59-a8b9-4136-8af1-62e71fc020b0)

**Comment by kcassam** [comment]
1:5 meant… 1:05 😅

**Comment by flymia** [comment]
Fixed by #47 - Again thank you very much for this. It means very much for me when other people contribute stuff to my projects.
